{% set name = "pcdsdevices" %}
{% set version = "8.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pcdsdevices/archive/v{{ version }}.tar.gz
  sha256: b1c0f0f9165f91ce7c2e2dab422687233c838d2523dd0d68bdc550d7e7590ecf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - bluesky-base >=1.6.4
    - happi
    - jsonschema
    - lightpath-base >=1.0.5
    - matplotlib-base
    - numpy
    - ophyd >=1.7.0
    - pcdscalc >=0.3.3
    - pcdsutils >=0.11.0
    - prettytable
    - pyepics >=3.4.2
    - pytmc >=2.14.0
    - pyyaml
    - schema
    - scipy
    - sympy
  run_constrained:
    - pmgr >=2.0.2
    - typhos >=2.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  doc_url: https://pcdshub.github.io/pcdsdevices/
  dev_url: https://github.com/pcdshub/pcdsdevices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Collection of Ophyd device subclasses for IOCs unique to the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - tangkong
    - zllentz
